// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Reactive;
using System.Reactive.Disposables;
using System.Reactive.Linq;
using CloudDataProtection.App.iOS.Datasources;
using CloudDataProtection.App.iOS.Segues;
using CloudDataProtection.App.Shared.ViewModels;
using Foundation;
using ReactiveUI;
using UIKit;

namespace CloudDataProtection.App.iOS
{
	public partial class AdminDashboardViewController : ReactiveViewController<AdminDashboardViewModel>
	{
		private NameViewModel _details;

		private UIRefreshControl RefreshControl => NamesTableView.RefreshControl ??= new UIRefreshControl();
		
		public AdminDashboardViewController(IntPtr handle) : base(handle)
		{
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();

			ViewModel = new AdminDashboardViewModel();

			_details = null;
			
			NamesTableView.RegisterNibForCellReuse(NameTableViewCell.Nib, NameTableViewCell.Identifier);
			NamesTableView.SectionHeaderTopPadding = 0;

			this.WhenActivated(d =>
			{
				this.WhenAnyValue (v => v.ViewModel.Rows)
					.Where (_ => NamesTableView.Source == null)
					.Subscribe (rows => NamesTableView.Source = new NameDataSource (NamesTableView, rows, ItemSelected))
					.DisposeWith (d);
				
				Observable.FromEventPattern (h => RefreshControl.ValueChanged += h, h => RefreshControl.ValueChanged -= h)
					.Subscribe (_ => OnRefresh ())
					.DisposeWith (d);

				this.Bind(ViewModel, vm => vm.SearchQuery, a => a.SearchTextField.Text)
					.DisposeWith(d);
			});
		}

		private void OnRefresh()
		{
			RefreshControl.EndRefreshing ();

			Observable.Return(Unit.Default).InvokeCommand(ViewModel.Search);
		}

		private void ItemSelected(NameViewModel model)
		{
			if (_details == null)
			{
				_details = model;
				PerformSegue(SegueIdentifiers.ShowNameDetail, this);
			}
		}
		
		public override void PrepareForSegue(UIStoryboardSegue segue, NSObject sender)
		{
			base.PrepareForSegue(segue, sender);

			if (segue.Identifier == SegueIdentifiers.ShowNameDetail)
			{
				((NameDetailViewController)segue.DestinationViewController).NameViewModel = _details;
			}
		}

		partial void UnwindToAdminDashboard(UIStoryboardSegue segue)
		{
			_details = null;
		}
	}
}
