// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Reactive.Disposables;
using System.Reactive.Linq;
using CloudDataProtection.App.iOS.Datasources;
using CloudDataProtection.App.iOS.Segues;
using CloudDataProtection.App.Shared.ViewModels;
using Foundation;
using ReactiveUI;
using UIKit;

namespace CloudDataProtection.App.iOS
{
	public partial class AdminDashboardViewController : ReactiveTableViewController<AdminDashboardViewModel>
	{
		private NameViewModel _details;
		
		public AdminDashboardViewController(IntPtr handle) : base(handle)
		{
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();

			ViewModel = new AdminDashboardViewModel();

			_details = null;

			this.WhenActivated(d =>
			{
				this.WhenAnyValue (v => v.ViewModel.Rows)
					.Where (_ => TableView.Source == null)
					.Subscribe (rows => TableView.Source = new NameDataSource (TableView, rows, ItemSelected))
					.DisposeWith (d);
			});
		}

		private void ItemSelected(NameViewModel model)
		{
			if (_details == null)
			{
				_details = model;
				PerformSegue(SegueIdentifiers.ShowNameDetail, this);
			}
		}

		public override void PrepareForSegue(UIStoryboardSegue segue, NSObject sender)
		{
			base.PrepareForSegue(segue, sender);

			if (segue.Identifier == SegueIdentifiers.ShowNameDetail)
			{
				((NameDetailViewController)segue.DestinationViewController).NameViewModel = _details;
			}
		}

		partial void UnwindToAdminDashboard(UIStoryboardSegue segue)
		{
			_details = null;
		}
	}
}
