// This file has been autogenerated from a class added in the UI designer.

using System;
using CloudDataProtection.App.Shared.ViewModels;
using ReactiveUI;

namespace CloudDataProtection.App.iOS
{
	public partial class NameTableViewCell : ReactiveTableViewCell<NameViewModel>
	{
		public NameTableViewCell(IntPtr handle) : base(handle)
		{
		}

		public override void AwakeFromNib()
		{
			base.AwakeFromNib();

			this.WhenAnyValue(cell => cell.ViewModel.Name)
				.BindTo(this, cell => cell.NameLabel.Text);
		}
	}
}
